### PR TITLE
Update manifest.json to support Thunderbird Supernova

### PR DESCRIPTION
**Pull request by CodeJordan23**
Bump `strict_max_version` to `115.*`

### CODE REVIEW

**Comment by CodeJordan23** [comment]
I prematurely updated to Supernova, which does not support the official `cb_thunderlink` extension yet.

Because my workflow requires this great extension I tried to get it running under Supernova. This is the minimum change required. I was happy that I did not have to tinker with `manifest_version` and `permissions` :sweat_smile:.

Anyway I could get a working Supernova extension.

**Comment by bramadams** [comment]
Hi,

After installing the new release with this patch, I am able to copy a thunderlink from TB, but I am unable to paste-and-jump to a thunderlink, neither using the cb_thunderlink button in TB nor the plugin shortcut. It used to work pre-115.*.

TB basically shows a "nounDef is undefined" error from line 69 in cb_api.js, which calls newQuery on line 1832 of Gloda.jsm, see the attached screenshot with the full stacktrace.

Rebuilding the global index does not seem to fix the issue.

@CodeJordan23 : Are you able to paste a link in TB and jump to that email?

**Comment by CamielBouchier** [comment]
Hi,

Following in background (I am not yet on 115 and thus cannot reproduce.
Based on my reading of the stacktrace I wonder if it's really an issue of cb_thunderlink. 
My first suggestion would be: does a manual search for the message-id (or any other feature of the message) work?
Let me know if I can be of any help ...

Camiel B.

**Comment by bramadams** [comment]
Thanks for the quick reply.

Yes, searching on the subject of that email works within TB, and using sqlite3 on global-messages-db.sqlite I can retrieve the email information based on the message id. I'll try to poke some more.

**Comment by CamielBouchier** [comment]
Can you insert some console.log messages to identify which call actually fails? 

is it the Gloda.newQuery?
Or the headerMessageId?
Or the getCollection?

I am still suspecting some change in the gloda that interferes. 
@CodeJordan23: any insights from your end, does it work?

**Comment by bramadams** [comment]
Hi @CamielBouchier, I fixed the issue in cb_api.js, will send a pull request.

**Comment by CamielBouchier** [comment]
After merging in I needed to change it a bit to stay compatible with pre-115 versions. 
Can you check if the result still works for you now?
Camiel B.

**Comment by bramadams** [comment]
Hi @CamielBouchier , yes the updated code still works on 115, thanks for making the modifications.

**Comment by CamielBouchier** [comment]
@bramadams : Thanks for the confirmation!  Will make a new release next couple of days.
Camiel B.

**Pull request merged**
